### ISSUE TITLE
Strange behaviour when trying MPI

### ISSUE THREAD

**Issue by JesusTorrado** [rjw57/MultiNest#3]
Dear Rich,

There is something I cannot figure out, and probably is in my system, but there it goes, just in case:

I try and succeed compiling MultiNest with mpi (all the :code:`libmultinest_mpi.*` are built). The problem comes when I try to run any of the examples in the :code:`bin/` folder:

..code::

```
$ mpirun -np 2 eggbox
*****************************************************
 MultiNest v3.4
 Copyright Farhan Feroz & Mike Hobson
 Release Oct 2013

 no. of live points = 1000
 dimensionality =    2
 *****************************************************
 Starting MultiNest
 *****************************************************
 MultiNest v3.4
 Copyright Farhan Feroz & Mike Hobson
 Release Oct 2013

 no. of live points = 1000
 dimensionality =    2
 *****************************************************
 Starting MultiNest
 generating live points
 generating live points
 live points generated, starting sampling
 live points generated, starting sampling
Acceptance Rate:                        1.000000
Replacements:                               1050
Total Samples:                              1050
Nested Sampling ln(Z):                 -1.411483
Importance Nested Sampling ln(Z):     235.563887 +/-  0.627918
Acceptance Rate:                        1.000000
Replacements:                               1050
Total Samples:                              1050
Nested Sampling ln(Z):                 -1.411483
Importance Nested Sampling ln(Z):     235.563887 +/-  0.627918
Acceptance Rate:                        0.997280
Replacements:                               1100
Total Samples:                              1103
Nested Sampling ln(Z):                  0.243307
```

etc, etc.

As you see, the "header" is printed twice, which I would interpret as MultiNest just running twice, instead of running two threads with MPI.

Any clue?

Best,
Jesús

**Comment by rjw57** [comment]
> As you see, the "header" is printed twice, which I would interpret as MultiNest just running twice, instead of running two threads with MPI.

MPI does indeed run two copies of the program in two processes. MPI doesn't use multi threading, which is one possible form of parallelism (the "share everything by default" approach). It uses message passing (the "share nothing by default" approach) which is the source of "M" and "P" in MPI.

I'd read up on how MPI works if you're confused about this. Spawning _n_ instances of the target program is intended behaviour for MPI. It's most obvious why when considering multiple co-operating machines, often termed "nodes" in MPI. There the multi-threaded approach is meaningless because each machine has completely separate memory, CPU, etc, etc.

**Comment by JesusTorrado** [comment]
Yeah, that's true, sorry. Shitty explanation from me. I got a better grip on MPI later yesterday, finally. Thanks!

Anyway, if I take a look at the :code:`nested.F90`, I see the header under a :code:`if(my_rank==0)` (line 194--220). Wouldn't it mean that, if everything was correctly compiled and run, an :code:`mpirun` should still show the header just once?

**Comment by rjw57** [comment]
Note lines 76-90 in `nested.F90`.

**Comment by JesusTorrado** [comment]
Thanks! I will put some debug prints and see what's happening.

**Comment by teja781** [comment]
Sorry to resurrect an old closed thread, but I am having the exact same issue with Multinest_v3.11. Is there a  fix for this issue?

Thanks
