### ISSUE TITLE
Indicate how close to stopping conditions

### ISSUE THREAD

**Issue by andrewfowlie** [rjw57/MultiNest#4]
I know that the MN terminates if (amongst other things)

```
ln(Z) -  current_volume * ln(max_like) < tolerance
```

could the MN code report that quantity and the status of all stopping conditions? It would be quite helpful.

**Comment by andrewfowlie** [comment]
I've implemented this myself in this project: https://github.com/innisfree/watch_multinest

The Python scripts read the MN output and monitor the stopping conditions per mode.

**Comment by rjw57** [comment]
Hi @innisfree 

Thanks for your interest in MultiNest but this is just a personal fork of the project. The project's home page is https://ccpforge.cse.rl.ac.uk/gf/project/multinest/ and there should be contact info there.
